apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-deployment
  template:
    metadata:
      labels:
        app: database-deployment
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: hardtocrack111
        ports:
        - containerPort: 3306
