apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-svc"
spec:
  ports:
  - name: "http"
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.serviceType }}
