# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: {{ .Values.appName}}
#   name:  {{ .Values.appName }}
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend-deployment
#   template:
#     metadata:
#       labels:
#         app: frontend-deployment
#     spec:
#       containers:
#       - image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/frontend:1.1
#         name: frontend
#         ports:
#         - containerPort: 80
